source 'https://rubygems.org'
gem 'fpm', '=1.9.2'
gem 'rake', '=11.2.2'
gem 'colorize', '=0.8.1'
gem 'POpen4', '=0.1.4'
gem 'rpm', :git => 'https://gitlab.com/harbottle/ruby-rpm-ffi.git'
gem 'filesize', '=0.1.1'
gem 'ruby_expect', '=1.7.4'
gem 'concurrent-ruby', '=1.0.2'
